version: '3.8'
services:
  rag:
    container_name: rag
    image: benaya7/rag:1.0.2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_INIT=false
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: pgvector/pgvector:0.7.0-pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 5s
      timeout: 60s
      retries: 5
  ollama:
    container_name: ollama-offline
    image: benaya7/ollama-offline:mistral_nomic-1
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ollama-2:/root/.ollama

volumes:
  ollama-2: