#spring.ai.openai.api-key=dummy
logging:
  level:
    org:
      benaya:
        ai:
          rag:
            controller: DEBUG
spring:
  mvc:
    async:
      request-timeout: -1
  application:
    name: rag
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  ai:
    retry:
      backoff:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 4
      max-attempts: 20
    ollama:
      embedding:
        model: nomic-embed-text
        options:
          top-k: 3
          num-thread: 8
          num-ctx: 8192
          num-batch: 768
        enabled: true
      base-url: http://localhost:11434
      chat:
        model: llama3-gradient
        options:
          num-ctx: 64000
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        database-name: "default"
        collection-name: "vector_store1"
        index-type: ivf_flat
        metric-type: cosine
        embedding-dimension: 768
init:
  database: ${INIT_DATABASE:false}
#    openai:
#      base-url: ${LLM_BASE_URL_OPENAI_TYPE://localhost:8081}
#      embedding:
#        options:
#          model: llama3-gradient
#      api-key: ${LLM_API_KEY_OPENAI_TYPE:dummy}
#      chat:
#        base-url: